baseURL = "https://librecorps.github.io/resources/"
theme = "dot-hugo-documentation-theme"
defaultContentLanguage = "en"
home = "/"

[params]
primaryColor = "#02007e"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

[Languages]

  # English Language
  [Languages.en]
  languageName = "En"
  weight = 1
  languageCode = "en"
  title = "LibreCorps Resources"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "LibreCorps"
  copyright = "Creative Commons BY-NC-SA 4.0"

    # navigation
    [Languages.en.menu]

      [[Languages.en.menu.main]]
        weight = 2
        name = "FAQ"
        url = "faq"

      [[Languages.en.menu.main]]
        weight = 2
        name = "pages"
        url = "pages"
        hasChildren = true

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "Community Strategy"
          url = "community"
          weight = 2

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "FOSS Product Management"
          url = "product-management"
          weight = 3

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "AI Ethics & Transparency"
          url = "ai"
          weight = 4

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "Tooling & Automation"
          url = "tooling"
          weight = 5

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "Outreach & Marketing"
          url = "outreach"
          weight = 6

          [[Languages.en.menu.main]]
          parent = "pages"
          name = "Legal"
          url = "legal"
          weight = 7

    # banner
    [Languages.en.params.banner]
      title = "LibreCorps Knowledge Base"
      description = "Resources for building sustainable open source projects, curated by RIT LibreCorps"
      image = "images/banner.jpg"
      placeholder = "Have a question? Search our resources"

    # Topics
    [Languages.en.params.topics]
      title = "Browse by category"

    # footer social icon
    [[Languages.en.socialIcon]]
      icon = "ti-github"
      linkURL = "https://github.com/librecorps/"

    [[Languages.en.socialIcon]]
      icon = "ti-twitter-alt"
      linkURL = "https://twitter.com/jflory7"

    [[Languages.en.socialIcon]]
      icon = "ti-vimeo-alt"
      linkURL = "#"

    [[Languages.en.socialIcon]]
      icon = "ti-instagram"
      linkURL = "#"
